version: "3.3"
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ./komga/config:/config
      - ./komga/data:/data
    ports:
      - "25600:25600"
    restart: unless-stopped
