version: "3.9"
services:
  discount-bandit:
    image: cybrarist/discount-bandit:v3.1.2-amd64
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: ""
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHANNEL_ID: ""
      DEFAULT_USER: "test"
      DEFAULT_EMAIL: "docker@test.com"
      DEFAULT_PASSWORD: "thisismypassword"
      APP_TIMEZONE: UTC
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
    restart: unless-stopped
