version: "3.9"
services:
  endurain:
    container_name: endurain-app
    image: ghcr.io/joaovitoriasilva/endurain:latest
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:17.5
    container_name: endurain-postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endurain"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
